# This is a basic workflow to help you get started with Actions

name: NekoYyangのAutoSignIn

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  schedule:
    - cron: '0 21 * * *' 
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  SignIn:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a set of commands using the runners shell
      - name: GetToken
        run: |
         echo "[↓] Requesting WebAPI..."
         echo ""
         curl -A 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.100 Safari/537.36' -X POST -H "'Content-type':'application/json'"  https://https.ghs.wiki:7002/API\?type\=login\&loginType\=email\&account\=${{ secrets.EMAIL }}\&password\=${{ secrets.PASSWORD }} > getToken.info
         echo ""
         sleep 3
      - name: SaveToken
        run: |
         echo "[+] Saving Token..."
         cut -c 35-70 getToken.info > token.info
         sleep 3
      - name: SignIn
        run: |
         echo "[+] Checking Token..."
         token=$(cat token.info)
         echo "[+] Start SignIn"
         echo ""
         curl -i -A 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.100 Safari/537.36' -X POST -H "'Content-type':'application/json'" https://https.ghs.wiki:7002/API\?type\=signIn\&token\=$token > info.json
         echo ""
         sleep 3
      - name: Report
        run: |
          echo "::group::result"
          coin=$(cat info.json | grep -o '"coin":[^,]*' | cut -d':' -f2)
          luck=$(cat info.json | grep -o '"luck":[^,]*' | cut -d':' -f2)
          luckmessage=$(cat info.json | grep -o '"luckMessage":[^,]*' | cut -d'"' -f4)
          signinmessage=$(cat info.json | grep -o '"signInMessage":[^,]*' | cut -d'"' -f4)
          echo "MossFrp 自动签到"
          echo "银币："$coin
          echo " 人品："$luck
          echo $luckmessage
          echo $signinmessage
          echo "::endgroup::"
